### ISSUE TITLE
Compatibility with Bronze Mod by June \\ 1.21

### ISSUE THREAD

**Issue by makumaku1974** [mrsterner/Geocluster#11]

**Comment by mrsterner** [comment]
Geocluster has Tin built-in, just make a datapack disabling Tin from Bronze mod and add a deposit from Geocluster.

The ore feature can be disabled by tag ``tags/worldgen/placed_feature/ores_to_remove.json``, bronze mods tin features is called ``"ore_tin"`` so just add that

**Comment by makumaku1974** [comment]
okay thanks.

**Comment by makumaku1974** [comment]
wait does polymorph support it? even without the disable datapack?
