### ISSUE TITLE
1.21 Xray Bug \\ Still appears in 1.3.5

### ISSUE THREAD

**Issue by makumaku1974** [mrsterner/Geocluster#14]
![2024-07-02_23 29 08](https://github.com/mrsterner/Geocluster/assets/129804277/7bfa7cb9-972b-426d-b087-2f5d37206643)

![Screenshot 2024-07-02 232940](https://github.com/mrsterner/Geocluster/assets/129804277/a08ba956-77ba-45fe-964a-382e37ab5397)

**Comment by makumaku1974** [comment]
This is done on Creative mode.

**Comment by mrsterner** [comment]
![image](https://github.com/mrsterner/Geocluster/assets/32911664/409d1fae-97e7-4f3a-96f9-24b7a248a0d4)

Don't know what to tell you, issue is not reproducable
