### ISSUE TITLE
Not sure if its to blame but version .2 is crashing my game in nether.

### ISSUE THREAD

**Issue by Cosmoros-git** [mrsterner/Geocluster#6]
[crash-2023-07-26_12.20.17-server.txt](https://github.com/mrsterner/Geocluster/files/12171185/crash-2023-07-26_12.20.17-server.txt)

**Comment by Cosmoros-git** [comment]
Okey tested it on previus version and it still crashes

**Comment by mrsterner** [comment]
Oh thats dumb, ill fix it when i get home from work
